# Generated by Django 6.0.5 on 2026-05-07 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('name_ru', models.CharField(blank=True, default='', max_length=100, verbose_name='Название (RU)')),
                ('name_tj', models.CharField(blank=True, default='', max_length=100, verbose_name='Название (TJ)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя мастера/гида')),
                ('specialty', models.CharField(max_length=150, verbose_name='Специализация')),
                ('bio', models.TextField(verbose_name='Описание')),
                ('contact', models.CharField(max_length=150, verbose_name='Контакты')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Мастер/Гид',
                'verbose_name_plural': 'Мастера и гиды',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('name_ru', models.CharField(blank=True, default='', max_length=100, verbose_name='Название (RU)')),
                ('name_tj', models.CharField(blank=True, default='', max_length=100, verbose_name='Название (TJ)')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (RU)')),
                ('name_tj', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (TJ)')),
                ('inf_type', models.CharField(choices=[('hotel', 'Гостиница'), ('restaurant', 'Ресторан'), ('transport', 'Транспорт'), ('shop', 'Магазин'), ('hospital', 'Больница'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_tj', models.TextField(blank=True, default='', verbose_name='Описание (TJ)')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, default='', verbose_name='Сайт')),
                ('image', models.ImageField(blank=True, null=True, upload_to='infrastructure/', verbose_name='Фото')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Инфраструктура',
                'verbose_name_plural': 'Инфраструктура',
            },
        ),
        migrations.CreateModel(
            name='CulturalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (RU)')),
                ('title_tj', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (TJ)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_tj', models.TextField(blank=True, default='', verbose_name='Описание (TJ)')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.category', verbose_name='Категория')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Культурный объект',
                'verbose_name_plural': 'Культурные объекты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Автор')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1-5)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism.culturalobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('title_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (RU)')),
                ('title_tj', models.CharField(blank=True, default='', max_length=200, verbose_name='Название (TJ)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_tj', models.TextField(blank=True, default='', verbose_name='Описание (TJ)')),
                ('duration', models.CharField(max_length=100, verbose_name='Продолжительность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена (в сомони)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='routes/', verbose_name='Фото маршрута')),
                ('objects_included', models.ManyToManyField(blank=True, to='tourism.culturalobject', verbose_name='Объекты маршрута')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('cultural_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.culturalobject', verbose_name='Культурный объект')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tourism.touristroute', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'ordering': ['order'],
            },
        ),
    ]
