# Generated by Django 6.0.5 on 2026-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalobject',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Фото'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Фото'),
        ),
        migrations.AlterField(
            model_name='touristroute',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Фото маршрута'),
        ),
    ]
